### ISSUE TITLE
Vue 3 compatability

### ISSUE THREAD

**Issue by itpropro** [Zulko/eagle.js#103]
I just tried eagle js and it's so fun to use! Is this project still being maintained and are there any plans to support Vue 3?

**Comment by yaodingyd** [comment]
I guess u mean to support composition API? I'm working one a prototype

**Comment by sosensible** [comment]
I am also wondering if the mixin approach could be simplified?

**Comment by itpropro** [comment]
> I am also wondering if the mixin approach could be simplified?

Hey @sosensible, unfortunately, this project seems  dead, the last update is from 2019. Try out sli.dev ;)
