### ISSUE TITLE
Library is not easily included into project

### ISSUE THREAD

**Issue by Wattos** [Zulko/eagle.js#14]
First off, great work! This looks really good.

I am trying to include eagle.js as a library into my project, but it seems to be a lot of trouble to get running.

This is the following steps I exectuted:

`npm install --save eagle.js`

`import Eagle from 'eagle.js'` in my main.js

Unfortunately, it seems that eagle.js is no way build, so it will be build during my build process. That means I need to fetch all the dependencies which eagle.js requires. such as:

```
    "babel-plugin-transform-runtime": "^6.23.0",
    "babel-plugin-component": "0.9.0",
    "babel-preset-es2015": "^6.22.0",
    "babel-preset-stage-2": "^6.22.0"
    "pug"...
```

Etc. This means the the eagle library is not scoped, so each time I would like to update to a new version, I will have a bad time. I would really like to use this framework, but as it is right now, it is not possible to reuse.

**Comment by Zulko** [comment]
I'm a complete npm beginner unfortunately, I understand the problem but I may not be the best person to solve it (very very little time at the moment), so if yourself or anyone else wants to tackle this, I'm all for it.

**Comment by ktsn** [comment]
Hello, I'm very interested in this library and want to include my app.
If anyone does not try to solve this yet, I'd like to work for it.

**Comment by Zulko** [comment]
Thanks ! No one is working on this as far as I can tell so feel free :)

**Comment by Zulko** [comment]
Should be fixed by the new release (hopefully, didn't have time to test)
