### ISSUE TITLE
wether it support mobile phone

### ISSUE THREAD

**Issue by tgxpuisb** [Zulko/eagle.js#2]
i'm looking for a framework which can change theirs pages like native(iOS)

example: when the router is changing, the page can slide-in from the right, and the page can slide-out from right when i leave 

i try to resolve it, but if the page can scroll, i can not made the page in right position when the page is changing

**Comment by yaodingyd** [comment]
@tgxpuisb  can you elaborate on the native behavior you want to achieve? Right now your description just seems like a transition effect.

**Comment by yaodingyd** [comment]
Will reopen if issue has more details.
