### ISSUE TITLE
feature request: **PERMALINKS** Go to a specific slide.

### ISSUE THREAD

**Issue by c0b** [Zulko/eagle.js#24]
like https://webslides.tv/#slide=4 **PERMALINKS**
Go to a specific slide.

I found the eagle.js from https://bestof.js.org/tags/presentation/trending/this-month looking for some revealjs alternative, one of the common feature available in others is the PERMALINKS but still lack in eagle.js ?

**Comment by c0b** [comment]
reveal.js uses http://lab.hakim.se/reveal-js/#/6 as the permalink to specific slide,

can this url https://zulko.github.io/eaglejs-demo/#/introducing-eagle be redesigned to similar like

https://zulko.github.io/eaglejs-demo/introducing-eagle/#/<slide-number> or the webslides style by `#slide=4`

**Comment by yaodingyd** [comment]
Because `vue-router` is not a dependency to eagle, I don't think implement permalinks inside eagle would be a good idea. But you can easily achieve this by use `vue-router`.

For example,  in project's built-in example, add params to route paths:
```javascript
slideshows.list.forEach(function (slideshow) {
  routes.push({
    path: '/' + slideshow.infos.path + '/:slide/:step',
    component: slideshow
  })
  routes.push({
    path: '/' + slideshow.infos.path,
    component: slideshow
  })
})
```

And inside a `Slideshow`, add watchers to update URL when slides changes, and update slides when URL changes:
```javascript
 ....
  methods: {
    ....
     updateSlides: function () {
      this.currentSlideIndex = +this.$route.params.slide
      this.$nextTick(() => {
        this.step = +this.$route.params.step
      })
    },
    updateURL: function () {
      this.$router.push(`/${this.$route.path.split('/')[1]}/${this.currentSlideIndex}/${this.step}`)
    }
  },
  mounted: ['updateSlides'],
  watch: {
    '$route': 'updateSlides',
    step: 'updateURL',
    currentSlideIndex: 'updateURL'
  }
```
You can use the above snippet as a mixins to include into your `Slideshow` component.

Demo link is here [http://eaglejspermalink.surge.sh/#/introducing-eagle/2/1](http://eaglejspermalink.surge.sh/#/introducing-eagle/2/1)

**Comment by c0b** [comment]
agree, that may not be part of core functions of eagle.js but could you deploy to the https://zulko.github.io/eaglejs-demo/ ? or switch to use http://eaglejspermalink.surge.sh as demo site?

just because from https://bestof.js.org/tags/presentation you can see: all js based presentation framework has the perma links as a **feature** it's pretty much a standard

and 'eaglejs-demo' can be called (or alias or rename) as eaglejs-boilerplate?

**Comment by yaodingyd** [comment]
As eagle doesn't have a dependency on any routing solutions for now, this is for user land to implement.

**Comment by c0b** [comment]
So eaglejs-demo can be maintained as a more user-friendly eaglejs-boilerplate? then users can just copy from boilerplate and just modify content without too much hacking of js code? part of #30 have a list of nice-to-have features for maintainer roadmap?

**Comment by yaodingyd** [comment]
The current eaglejs-demo does the basic setup already. This project is started with being hackable in mind, so all components are very "raw" and scaffolding is very basic . However there is another issue for vue-cli template and that issue is open for tracking this feature.
