### ISSUE TITLE
[Safari] Doesn't work some features

### ISSUE THREAD

**Issue by dimpiax** [Zulko/eagle.js#3]
Arrows' flow and "Ctrl + right" / left doesn't work.
Sliding gesture skippes animation on arrival page.

**Comment by Zulko** [comment]
Thanks for this. I cant reproduce the arrow problem as I dont have any safari access right now, but i'll have a look first chance i get.

Sliding is not supported right now (because of browser compatibility problems), it's just tapping left or right of the screen.

**Comment by peterblazejewicz** [comment]
> I cant reproduce the arrow problem as I dont have any safari access right now

That's correct (mac OS Sierra/Safari 10.*). I'll dig into this locally

**Comment by peterblazejewicz** [comment]
- this won't work in some Safari versions:
http://caniuse.com/#feat=keyboardevent-key
- this valuates to false:
```
if (this.keyboardNavigation &&
          (this.currentSlide.keyboardNavigation || evt.ctrlKey)) {
```

**Comment by dimpiax** [comment]
What if switch to `CMD`?

**Comment by dimpiax** [comment]
Try this:
```javascript
$(window).keydown(function(e) {
  const code = e.keyCode
  if (code === 37 || code === 39) {
    if (e.metaKey) {
      console.log(`slide to ${code === 37 ? 'left' : 'right'}`);
    }
  }
})
```

Can contribute after lunch ;)

**Comment by QuentinRoy** [comment]
No need for a new dependency. `addEventListener('keydown', () => { \* ... *\ });` works just as well.

**Comment by yaodingyd** [comment]
Please use command + right/left in Mac as ctrl + right/left is move screen by default.
