### ISSUE TITLE
npm run dev -> for demo

### ISSUE THREAD

**Issue by Bear4** [Zulko/eagle.js#34]
error  in ./src/slideshows/themes-slideshow/ThemesSlideshow.vue
error  in ./src/slideshows/introducing-eagle/AwesomeInsertedSlide.vue
error  in ./src/slideshows/introducing-eagle/FiguresSlide.vue
error  in ./src/slideshows/eagle-recipes/DemoSlideshow.vue
error  in ./src/slideshows/introducing-eagle/components/EndCredits.vue 
error  in ./src/slideshows/introducing-eagle/AwesomeEmbeddedSlideshow.vue
...
Module build failed: Error: Cannot find module 'node-sass'     
And erron on browser http://localhost:8080/
Cannot GET/

**Comment by Zulko** [comment]
I don't get it and I don't have much time to work on it. Is the demo repo broken ?

**Comment by Bear4** [comment]
Seems to lack of 'node-sass' module ...

**Comment by yaodingyd** [comment]
@Bear4 Your node-sass installment fails for reason not listed here in your issue. Try reinstall node-sass:
```
npm install node-sass
```

If this fails too, try

```
npm install node-sass --no-bin-links
```

You can also delete your `package-lock.json` and `node_modules` and re-install whole dependencies.

**Comment by Zulko** [comment]
I'm not sure I get it, shouldn't "node-sass" be installed when running eagle's "npm install" ?

**Comment by yaodingyd** [comment]
@Bear4 If you still running into trouble setting up the demo project, please open up new issue [here](https://github.com/Zulko/eaglejs-demo/issues).
