### ISSUE TITLE
Missing CSS Dependencies

### ISSUE THREAD

**Issue by aminimalanimal** [Zulko/eagle.js#36]
Under **Usage**, the documentation says to `import 'eagle.js/dist/eagle.css'` into your main.js file.
I did this and don't see any styles applied.

I installed eagle.js via npm (`yarn add eagle.js`) into a project bootstrapped with `vue init webpack`.

Also, the documentation mentions that eagle supports `animate.css` transitions. Is `animate.css` included within `eagle.css` or is it a separate dependency that should be documented to be manually added?

**Comment by yaodingyd** [comment]
Yes, we do need a new release. Currently you can use `eagle.js/dist/theme/base.css`. And you need to import animate.css in your main file. README file will be updated.

@Zulko time for a new release?

**Comment by aminimalanimal** [comment]
Thanks @yaodingyd.

Sounds like the updated documentation should inform the user to add the following to the top of their main.js file:
```
import 'animate.css/animate.min.css'
import 'eagle.js/dist/eagle.css'
import 'eagle.js/dist/themes/base.css'
```

That helped out a lot. I now have the styles I was expecting.

**Comment by aminimalanimal** [comment]
There are still some anomalies in the documentation that I don't understand, and if you can help me suss them out, perhaps I can submit a PR with their corrections.

Under **slide** in the README, the example shows `:` vue-bindings on `enter` and `leave`. Was this intentional?
```
eg-transition(:enter='enter', :leave='leave')
```

In the [Introducing Eagle demo](https://zulko.github.io/eaglejs-demo/#/introducing-eagle), `enter` is applied directly to a `slide`. This isn't working for me. Perhaps `eg-transition` is always needed?
```
slide(enter='slideInLeft', :steps=4)
```

The above also occurs in [Eagle Recipes demo](https://zulko.github.io/eaglejs-demo/#/eagle-recipes):
```
slide(enter='fadeIn' leave='fadeOut')
```

```
slide(enter='bounceInRight' leave='bounceOutLeft')
```

**Comment by yaodingyd** [comment]
@aminimalanimal  Do you have a example repo and online sandbox I can look at?

**Comment by yaodingyd** [comment]
@aminimalanimal  The README do have typos and some confusing writings. Please submit a PR if you find one, and thanks!

**Comment by aminimalanimal** [comment]
@yaodingyd I thought I found typos, but that misunderstanding was happening because of the issue I'm having with `slide`. Let me see if I can set up a sandbox to demonstrate.

**Comment by aminimalanimal** [comment]
Alright, I got a sandbox set up. Took a while because it doesn't support pug. :P
Also, note that the sandbox forces me to set a static height on the slideshow to get it to appear.

[Sandbox - `enter` and `leave` transitions not working on `slide`](https://codesandbox.io/s/82mqm055zj?autoresize=1&module=%2Fcomponents%2FSlideShow.vue)

**Comment by yaodingyd** [comment]
@aminimalanimal  I'm so sorry. `0.1.3` have a breaking issue #33. For now you can use `0.1.2` but still there's a lot of console error you will see.

We will roll up a new release in no time.

**Comment by aminimalanimal** [comment]
@yaodingyd awww, no need to apologize—thanks for patching it so quickly! I just installed the new version and it works. (I like that you got rid of the need to `import 'eagle.js/dist/themes/base.css'`, too.) Closing. :)
