### ISSUE TITLE
Keyboard navigation disables all other keyboard-based browser interaction

### ISSUE THREAD

**Issue by flesser** [Zulko/eagle.js#37]
Is there a reason for [`evt.preventDefault()`](https://github.com/Zulko/eagle.js/blob/master/src/components/Slideshow.vue#L184) in the Slideshow component's `keydown` handler?

It prevents other keyboard shortcuts from working (like pressing F11 in Firefox to enter/leave fullscreen mode).

I just tested to remove that line in my local copy and have seen no negative side-effects so far.

**Comment by yaodingyd** [comment]
Good point. I'll look into this further.

**Comment by yaodingyd** [comment]
It seems the `preventDefault` is redundant and actually causing some issues (#3).

**Comment by yaodingyd** [comment]
fixed in `0.1.5`
