### ISSUE TITLE
Add diagram support

### ISSUE THREAD

**Issue by italomaia** [Zulko/eagle.js#41]
It would be quite nice to be able to easely create diagrams with eagle.

**Comment by yaodingyd** [comment]
What kind of diagrams do you want to use in eagle.js?

You can always use other vue diagram libraries inside eagle.js. Do you have
any special functionality in your mind?

**Comment by Zulko** [comment]
I agree with @yaodingyd, with Eagle your slideshow is a Vue project so you can embed any other diagram javascript framework. See [here](https://github.com/Zulko/eaglejs-demo/blob/master/src/slideshows/introducing-eagle/FiguresSlide.vue#L21-L22) for an example with Chart.js.

To see this example in action (warning, it's convoluted) go to the [demo slides](https://zulko.github.io/eaglejs-demo/#/introducing-eagle) and when you arrive at the form, switch off all the three topics. This will bring you to the secret slide, which features SVG and Chart.js diagrams.

**Comment by yaodingyd** [comment]
@italomaia I'll close this for now. Will reopen it ff you have any ideas coming up.
