### ISSUE TITLE
npm install issue

### ISSUE THREAD

**Issue by flipdav8** [Zulko/eagle.js#42]
Hi there,

Thanks for the work, this looks amazing!

I am having an issue. After npm install it says this 

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.5.0/win32-x64-57_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.5.0/win32-x64-57_binding.node":

Any suggestions?

**Comment by yaodingyd** [comment]
Are you using Node 9? If so downgrade to node 8.

**Comment by yaodingyd** [comment]
will reopen for more details.
