### ISSUE TITLE
Presenter mode

### ISSUE THREAD

**Issue by yaodingyd** [Zulko/eagle.js#45]
@Zulko I'm thinking adding a presenter mode with postMessage API. what do you think? Does it need to be in core or a plug-in is good?

**Comment by Zulko** [comment]
Hey, I think a plugin would be very nice if it's possible to make it as a plug-in, otherwise core. Sounds very interesting. If all goes as I expect I'll come back to this project in the next months.

**Comment by leomeloxp** [comment]
@yaodingyd Do you mean something like speaker notes? ie, having what you intend to say on one window and the slides on another? 

<details>
<summary>eg this example from Google Slides</summary>

![](https://i0.wp.com/alicekeeler.com/wp-content/uploads/2014/11/Screen-Shot-2014-11-20-at-2.47.32-PM.png)

</details>

This would be an awesome feature!

**Comment by yaodingyd** [comment]
@leomeloxp yes! This is a PR #46 and any reviews are welcome.

**Comment by leomeloxp** [comment]
@yaodingyd Awesome. Seen your comments there, looks promising. I got a talk coming up this weekend where I'll be using eagle.js for the slides. I'll try to checkout your PR version and test it before then (might even risk using it on my talk as it's for a local meet up).
