### ISSUE TITLE
[Scripts] Need to add basic scripts

### ISSUE THREAD

**Issue by dimpiax** [Zulko/eagle.js#5]
We need some scripts for build and tests in NPM.

**Comment by Zulko** [comment]
Not sure what you mean by "build script", but there is already the possibility to ``npm run build``.

**Comment by dimpiax** [comment]
Don't see here `scripts`: https://github.com/Zulko/eagle.js/blob/master/package.json

**Comment by yaodingyd** [comment]
Script is added in `0.1.2` release.
