### ISSUE TITLE
Suggestion: Import only throttle from lodash

### ISSUE THREAD

**Issue by larsenwork** [Zulko/eagle.js#56]
Either with https://www.npmjs.com/package/lodash.throttle or as part of babel using something like https://github.com/lodash/babel-plugin-lodash

Would shave maybe 100kb off the bundle size.

**Comment by yaodingyd** [comment]
Feature done in be034c7134eabef723137f7c3b2e31b67759168a

**Comment by larsenwork** [comment]
Yeah, saw that — great update 👍
