### ISSUE TITLE
Hammer.js integration

### ISSUE THREAD

**Issue by christianw** [Zulko/eagle.js#60]
At least for me, swiping does not work with `new Hammer(window)` on phones. It works fine on desktop browsers with the swiping emulation.

Changing `Hammer(window)` to `Hammer(getElementById('app'))` works out of the box for desktop and mobile.

Maybe you can change the example?

**Comment by yaodingyd** [comment]
I tested [this](https://codesandbox.io/s/2k3nv4xp) on my iphone SE Safari and Chrome, swiping works fine in both browser. Can you share a link?

**Comment by yaodingyd** [comment]
Closing for now. Happy to reopen and investigate if you have any updates.@christianw
