### ISSUE TITLE
Slides not Zoomable

### ISSUE THREAD

**Issue by nkoehring** [Zulko/eagle.js#62]
If you use the browser zoom, nothing changes.

**Comment by yaodingyd** [comment]
Can you specify what browser did you use? Maybe a gif or video would really help.

**Comment by yaodingyd** [comment]
Can reproduce. Investigating.

**Comment by yaodingyd** [comment]
This is more like a feature. This is because eagle.js dynamically set font size based on viewport size. Realjs has the same behavior. Anyway a new zoom feature is added.
