### ISSUE TITLE
Subslide doesn't update

### ISSUE THREAD

**Issue by chambas** [Zulko/eagle.js#64]
Using the example (https://github.com/Zulko/eaglejs-demo/tree/master/src/slideshows/eagle-recipes),
the subslide with the code 
`eg-code-block(lang='html').` 
doesn't update. No matter what you write in there it always show the first block that it was render.

**Comment by yaodingyd** [comment]
Demo project will be updated shortly.

**Comment by chambas** [comment]
And regarding this issue?

**Comment by yaodingyd** [comment]
Turns out to be a bug. Will fix this later.

**Comment by yaodingyd** [comment]
https://github.com/Zulko/eagle.js/blob/3c42d5009ee48f65730f6057d615ff096414b6ab/src/components/widgets/CodeBlock.vue#L27

`this.update` should run in `updated` life cycle hook too.

**Comment by yaodingyd** [comment]
Please checkout the latest eaglejs-demo.
