### ISSUE TITLE
Feature Request: Allow presenter mode toggle key to be defined and/or tuned off

### ISSUE THREAD

**Issue by alex-exerve** [Zulko/eagle.js#72]
Yesterday I was giving a presentation on making provide/inject in vue reactive. This slide deck includes areas where you can type a message. As I was typing a message, presenter mode popped up. While I appreciate presenter mode, I really want to turn it off without disabling keyboard navigation.

I'll see if i can add a PR with a potential solution for it this evening.

**Comment by Zulko** [comment]
It seems that this wont happen if you disable keyboard navigation for the slideshow or the individual slide.

**Comment by alex-exerve** [comment]
Correct, but seeing as how i was using keyboard navigation, i should be able to reassign the hardcoded presenter mode key.
