### ISSUE TITLE
QUESTION: How would I remote control a slide show

### ISSUE THREAD

**Issue by netflakes** [Zulko/eagle.js#80]
Hi there this is question not an issue - just not sure where to ask this - I wrote a small presentation app using React and Reveal js to remote control presentations (presenter and viewer mode) and reveal js was very hacky to get the remote control feature to work. I am currently working on a VueJS version and would like to use eagle.js instead of reveal.js - am just not sure how I would `remote` control a presentation - in my React app I used sockets to communicate from the presenter to the client(s) and wrote some rather hacky js code to remote control via reveal.js - does eagle allow me via it's api to send remote - events ?

**Comment by yaodingyd** [comment]
Unfortunately eagle.js doesn't support your remote control mechanism. But I think once #75 is merged, it is fairly easy to implement something like you describe.

**Comment by yaodingyd** [comment]
It should be doable now that you can write you own plugin. You can create a socket connection, emit event on one end and listen to event in your plugin to do `nextStep` or `previousStep` on the other end.
