### ISSUE TITLE
Feature request: 1. Sub-Slides 2. CodeMirror sync

### ISSUE THREAD

**Issue by patarapolw** [Zulko/eagle.js#87]
BTW, I use Reveal.js with sub-slides to implement basic flash cards.

Now, I am also implementing a CMS, with YAML-frontmatter on the top + Slides separated by either --- (for major slides) and -- (for sub slides); and also allows Pug in place of Markdown.

**Comment by yaodingyd** [comment]
These are very easy to implement in user land. `Slide` in eagle is basically a regular vue component that you can have any children component inside. Beside we already have nested slides.

**Comment by patarapolw** [comment]
I need example for embedded mode, i.e. not fullscreen.

Currently I've got an error `Cannot create property 'direction' on string ''`,

```vue
<template lang="pug">
.eg-slideshow
  slide(enter="slideInRight" leave="slideOutRight")
    eagle-vertical(:content="slides[0] || ''" @lang="onLangChanged")
  slide(v-for="s in slides.slice(1)" :key="s" enter="slideInRight" leave="slideInRight")
    eagle-vertical(:content="s")
</template>
```

```vue
<template lang="pug">
.eg-slideshow
  slide(enter="slideInBottom" leave="slideOutBottom")
    raw(:code="slides[0] || ''" @lang="onLangChanged")
  slide(v-for="s in slides.slice(1)" :key="s" enter="slideInBottom" leave="slideOutBottom")
    raw(:code="s")
</template>
```

```vue
<script lang="ts">
import { Vue, Component, Prop, Emit } from "vue-property-decorator";
import MakeHTML from "@reveal-app/make-html";

...

Component
export default class Raw extends Vue {
  @Prop() code!: string;

  render(h: any){
    const {lang, html} = makeHTML.compile(this.code);
    this.emitLanguage(lang);

    const div = document.createElement("div");
    div.innerHTML = html;

    return h(Vue.compile(div.outerHTML));
  }

  @Emit("lang")
  emitLanguage(lang: string) {
    return lang;
  }
}
</script>
```

**Comment by patarapolw** [comment]
I have completed the project, with some problems.
- `previousSlide()` and `nextSlide()` does not trigger direction change.
- `previousStep()` and `nextStep()` stacks on each other, instead of disappearing by steps.
- No navigation buttons at lower right, like Reveal.js

<https://github.com/patarapolw/eagle-markdown> (https://patarapolw.github.io/eagle-markdown)

**Comment by yaodingyd** [comment]
> previousStep() and nextStep() stacks on each other, instead of disappearing by steps.

Can you make this an separate issue?

> No navigation buttons at lower right, like Reveal.js

This is managed in user land as Eagle.js doesn't provide any out of box UI for control. Though a plugin might be a good idea.
