### ISSUE TITLE
Programmatic navigation does not trigger `enter-prev` / `leave-prev`

### ISSUE THREAD

**Issue by patarapolw** [Zulko/eagle.js#88]
https://github.com/Zulko/eagle.js/issues/87#issuecomment-541231458

I have fixed it in my project, though. https://github.com/patarapolw/eagle-markdown/blob/990f5f63a53158bf7dcbb233c47b5ce8378db68e/src/components/EagleMarkdown.vue#L98

**Comment by yaodingyd** [comment]
PR welcome!

Corresponding code is in https://github.com/Zulko/eagle.js/blob/7a9e92ee9fb9189bdb6b264808393beece29045d/src/components/Slideshow.vue#L123 
and
https://github.com/Zulko/eagle.js/blob/7a9e92ee9fb9189bdb6b264808393beece29045d/src/components/Slideshow.vue#L138
