### ISSUE TITLE
Next on iPad only works for 1 press

### ISSUE THREAD

**Issue by imylomylo** [Zulko/eagle.js#9]
Not sure how to get you more info but happy to help.

Affects:
Chrome on iPad
Safari on iPad

iOS version 10.2.1

Maybe chrome/safari remote debugging - will try later this week.

**Comment by Zulko** [comment]
Sorry, im not sure what the bug is. What do you mean by "only works for 1 press" ?

**Comment by imylomylo** [comment]
Only the next slide (pressing side od screen) works once, then no more next
or previous slides (pressing next or previous areas does nothing).  So the
presentation on ipad is stuck on slide 2 with only the love heart heading.
 e.g.  On desktop, using the scroll wheel for next slide, the entire
presentation can be viewed.

So, bug is cannot progress through slides after one press.  Better?

Cheers

**Comment by jkwchui** [comment]
+1.  On iPad running iOS 10.3.3 I couldn't advance any slides.  Neither tapping edge of screen nor keyboard arrows work (on both Safari and Firefox).

**Comment by yaodingyd** [comment]
fixed in `0.1.5`.
