### ISSUE TITLE
Not really an issue: presentation template

### ISSUE THREAD

**Issue by christian-nils** [Zulko/eagle.js#95]
Hello Guys,

I do not know if any of you would be interested in a template for your presentation, but you can have a look to the one I have created: https://github.com/christian-nils/presentation_template.
It is based on https://github.com/JiriChara/the-past-present-and-future-of-javascript and I have added a couple of things: a menu listing the different slides references for vue-router (in `store.js`), and the possibility to modify the number of `steps` and the transitions for each slides (again, in `store.js`).

If you see any problem please let me know, I am not a JS developer by trade, so there should be some issues. 

I hope it can help you.

Thanks for the great EagleJS framework!

/CN

**Comment by yaodingyd** [comment]
Thank you! I can add this to README.
